
# E1 {#E1}



```{r , include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis', fig.width = 8)
 
 library(ggplot2)
 library(plotly)
 
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 library(tidyverse)
require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
 # library(sigma)
 source('functions.R')
```



```{r, echo=FALSE,results='asis'}


TLs<-list(c(48,30) )# , c(96,30))

for (TL in TLs){
gg<-ggplot()
momenta<-list(c(0,0,0,0,0,0),c(1,0,0,0,0,0),c(1,1,0,0,0,0),c(1,1,1,0,0,0))
p2<-c()
E1s<-c()
E1serr<-c()
cont_disp<-c()
latt_disp<-c()

T<- TL[1]
L<- TL[2]
dir<-paste("../out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output",dir,T,L)
cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)
m<-get_energy("E1_0",all_obs,mt)[1]  

for (ip in momenta){
  p2<-c(p2,  (2*pi/L)^2*(ip[1]^2+ip[2]^2+ip[3]^2   )  )
  cont_disp<-c(cont_disp, sqrt(m^2+(2*pi/L)^2*(ip[1]^2+ip[2]^2+ip[3]^2)  )   )
  hatp2=4* (sin(pi*ip[1]/L)^2+sin(pi*ip[2]/L)^2+sin(pi*ip[3]/L)^2   )
  #latt_disp<-c(latt_disp, acosh(1+ 0.5*(m^2+hatp2))  )
  latt_disp<-c(latt_disp, acosh(cosh(m)  +0.5*hatp2 )    )
}

gg<-add_plot("E1_0",all_obs,mt,gg,"no")
tmp<-get_energy("E1_0",all_obs,mt);E1s<-c(E1s,tmp[1]);E1serr<-c(E1serr,tmp[2])
gg<-add_plot("E1_0_p1",all_obs,mt,gg,"no")
tmp<-get_energy("E1_0_p1",all_obs,mt);E1s<-c(E1s,tmp[1]);E1serr<-c(E1serr,tmp[2])
gg<-add_plot("E1_0_p11",all_obs,mt,gg,"no")
tmp<-get_energy("E1_0_p11",all_obs,mt);E1s<-c(E1s,tmp[1]);E1serr<-c(E1serr,tmp[2])
gg<-add_plot("E1_0_p111",all_obs,mt,gg,"no")
tmp<-get_energy("E1_0_p111",all_obs,mt);E1s<-c(E1s,tmp[1]);E1serr<-c(E1serr,tmp[2])

fig<-ggplotly(gg,dynamicTicks = TRUE)%>% layout(title="fit" ,xaxis = list(title = "$t$",showexponent = "all", exponentformat = "e" , range=c(0, 14), autorange = F  ) ,
                      yaxis = list(title = "$\\log c(t)$",showexponent = "all", exponentformat = "e", autorange = T  ))  

print(htmltools::tagList(fig))
#assign("fig", fig, envir=parent.frame())
}

```


## dispersion relation

Here we compare the dispersion relation of the continuum 
$$
 E(p)^2=m^2+\vec p^2
$$
where $p_i=2\pi n_i/L$, with the one on the lattice

$$
  \cosh E(p)= \cosh E(0) + \frac{1}{2}\sum_{i=1}^{3} 4 \sin^2 \frac{p_i}{2}\,.
$$
In terms of parameters of the lagrangian the dispersion relation looks like 

$$
\cosh E(p)= 1 +\frac{m}{2}+ \frac{1}{2}\sum_{i=1}^{3} 4 \sin^2 \frac{p_i}{2}\,.
$$
so $E(0)$ is related to the parameter of the lagrangian $m$ as

$$
  \cosh E(0)= 1+\frac{m}{2}
$$

```{r, echo=FALSE,results='asis'}


TLs<-list(c(48,30)  )

cont_disp1<-c()
latt_disp1<-c()
p21<-c()
for (TL in TLs){
T<- TL[1]
L<- TL[2]
dir<-paste("../out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output",dir,T,L)
cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)
m<-get_energy("E1_0",all_obs,mt)[1]  

for (ip in (c(1:50)-1)/1e+2 ){
  p21<-c(p21,  ip*ip  )
  cont_disp1<-c(cont_disp1, sqrt(m^2+ip*ip)   )
  hatp2=4* (sin(ip/2)^2)
  latt_disp1<-c(latt_disp1, acosh(cosh(m)  +0.5*hatp2 )    )
}

}
df_disp <-data.frame("p2"=p21, "cont_disp"=cont_disp1 , "latt_disp"=latt_disp1)

```

```{r, echo=FALSE,results='asis'}

df <-data.frame("p2"=p2,"E1"=E1s,"E1err"=E1serr, "cont_disp"=cont_disp , "latt_disp"=latt_disp)
g1<- ggplot()+ geom_point(df ,mapping= aes(x=p2, y=E1)  )+
  geom_errorbar(df ,mapping= aes(x=p2, ymin=E1-E1err, ymax=E1+E1err),width=0.005  )+ theme_bw()+
  geom_line(df ,mapping= aes(x=p2, y=cont_disp,,color="cont"))+
  geom_line(df ,mapping= aes(x=p2, y=latt_disp,color="lattice"))
#  geom_line(df_disp ,mapping= aes(x=p2, y=cont_disp,,color="cont"))+
#  geom_line(df_disp ,mapping= aes(x=p2, y=latt_disp1,,color="lattice"))
fig<-ggplotly(g1, dynamicTicks = TRUE)%>%config(mathjax = 'cdn')   %>%layout(title="dispersion relation" ,xaxis = list(title = TeX("p^2"),showexponent = "all", exponentformat = "e" ,  autorange = T  ) ,
                      yaxis = list(title = TeX("E_1(P)"),showexponent = "all", exponentformat = "e", autorange = T  )) 
print(htmltools::tagList(fig))

```


```{r, echo=FALSE,results='asis',dev='tikz'}
df <-data.frame("p2"=p2,"E1"=E1s,"E1err"=E1serr, "cont_disp"=cont_disp , "latt_disp"=latt_disp)
lab_cont<-  "$E_1(p)-\\sqrt{ M^2 + p^2 }$"
g1<- ggplot()+ geom_point(df ,mapping= aes(x=p2, y=E1-cont_disp,
                                           color=lab_cont, shape=lab_cont )  )+
  geom_errorbar(df ,mapping= aes(x=p2, ymin=E1-E1err-cont_disp, ymax=E1+E1err-cont_disp,
                      color=lab_cont,shape=lab_cont ),width=0.005  )+ theme_bw() 
lab_latt<-paste0("$E_1(p)-\\cosh^-1\\left(\\cosh E(0) + \\frac{1}{2}\\sum_{i=1}^{3} 4 \\sin^2 \\frac{p_i}{2}\\right)$")
g1<- g1+ geom_point(df ,mapping= aes(x=p2, y=E1-latt_disp, color=lab_latt,shape=lab_latt)  )+
  geom_errorbar(df ,mapping= aes(x=p2, ymin=E1-E1err-latt_disp, ymax=E1+E1err-latt_disp, color=lab_latt,shape=lab_latt),width=0.005  ) 


fig<- myplotly(g1,"","$p^2$","$E_1(p)-\\mbox{dispersion relation}$",legend_position=c(0.1,0.1))
fig<- myplotly(g1,"","$p^2$","$E_1(p)-\\mbox{dispersion relation}$",legend_position=c(0.35,0.15), to_print = FALSE, save_pdf = "E1_0_disp_rel")


```



```{r, fig.height=0.1, fig.width=0.1}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```