## E2 Plateaux scan


```{r , include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
 #library(sigma)
 source('functions.R')
```

###  E2_0_p1

```{r, echo=FALSE,results='asis'}


TLs<-list(c(48,30),c(96,30)  )
gg<-ggplot()

for (TL in TLs){
T<- TL[1]
L<- TL[2]
dir<-paste("../out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_scan_plateaux",dir,T,L)
cat("\n####",file,'\n\n')

mt<-read_df(file);
all_obs<- get_all_corr(mt)
off=0+0.004*(T-48)/48
off1=0.004+0.004*(T-48)/48

gg<-add_plateaux_scan_plot("E2_0_p1",all_obs,mt,gg ,offset=off, ribbon=TRUE)
gg<-add_plateaux_scan_plot("E2_0_p1_ws",all_obs,mt,gg ,offset=off1, ribbon=FALSE)

}
ggplotly(gg,dynamicTicks = TRUE)%>% layout(title="fit" ,xaxis = list(title = "tmin+0.01*tmax",showexponent = "all", exponentformat = "e" , range=c(0, 14), autorange = F  ) ,
                      yaxis = list(title = "$E2 $",showexponent = "all", exponentformat = "e", autorange = F, range=c(0.37,0.39))) %>%config(mathjax = "cdn")
#DT::datatable(mt)
```


###  E2_0_p111

```{r, echo=FALSE,results='asis'}


TLs<-list(c(48,30),c(96,30)  )
gg<-ggplot()

for (TL in TLs){
T<- TL[1]
L<- TL[2]
dir<-paste("../out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_scan_plateaux",dir,T,L)
cat("\n####",file,'\n\n')

mt<-read_df(file);
all_obs<- get_all_corr(mt)
off=0+0.004*(T-48)/48
off1=0.004+0.004*(T-48)/48

gg<-add_plateaux_scan_plot("E2_0_p111",all_obs,mt,gg ,offset=off, ribbon=TRUE)
gg<-add_plateaux_scan_plot("E2_0_p111_ws",all_obs,mt,gg ,offset=off1, ribbon=FALSE)

}
ggplotly(gg,dynamicTicks = TRUE)%>% layout(title="fit" ,xaxis = list(title = "tmin+0.01*tmax",showexponent = "all", exponentformat = "e" , range=c(0, 14), autorange = F  ) ,
                      yaxis = list(title = "$E2 $",showexponent = "all", exponentformat = "e", autorange = F, range=c(0.5,0.55))) %>%config(mathjax = "cdn")
#DT::datatable(mt)
```
