## E3 (g=0.025)


```{r  include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
 #library(sigma)
 source('functions.R')
```




```{r, echo=FALSE,results='asis'}


TLs<-list(c(32,28) ) 
g<-0.025
for (TL in TLs){
gg<-ggplot()
T<- TL[1]
L<- TL[2]
dir<-paste("../../g0.025/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g%.6f_rep0_output",dir,T,L,g)
cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)

gg<-add_plot("E3_0_vev",all_obs,mt,gg,"yes")
gg<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"yes")
gg<-add_plot("E3_0_p11_vev",all_obs,mt,gg,"yes")
gg<-add_plot("E3_0_p111_vev",all_obs,mt,gg,"yes")
gg<-add_plot("E3_0_A1_vev",all_obs,mt,gg,"yes")
fig<-ggplotly(gg,dynamicTicks = TRUE)%>% layout(title="fit" ,xaxis = list(title = "$t$",showexponent = "all", exponentformat = "e" , autorange = T  ) ,
                      yaxis = list(title = "$\\log c(t)$",showexponent = "all", exponentformat = "e", autorange = T  ))  
print(htmltools::tagList(fig))
}
```




### residual plot 

```{r, echo=FALSE,results='asis'}

TLs<-list(c(32,28)  )
gg<-ggplot()
g<-0.025
for (TL in TLs){
T<- TL[1]
L<- TL[2]
dir<-paste("../../g0.025/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g%.6f_rep0_output",dir,T,L,g)
cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)

gg<-add_res_plot("E3_0_vev",all_obs,mt,gg,"no")
gg<-add_res_plot("E3_0_p1_vev",all_obs,mt,gg,"no")
gg<-add_res_plot("E3_0_p11_vev",all_obs,mt,gg,"no")
gg<-add_res_plot("E3_0_p111_vev",all_obs,mt,gg,"no")
gg<-add_res_plot("E3_0_A1_vev",all_obs,mt,gg,"no")

}

ggplotly(gg,dynamicTicks = TRUE)%>% layout(title="fit" ,xaxis = list(title = "$t$",showexponent = "all", exponentformat = "e" , range=c(0, 14), autorange = F  ) ,
                      yaxis = list(title = "$c(t)-\\mbox{fit}$",showexponent = "all", exponentformat = "e", autorange = T  )) 

```