# Fit QC3 (g=0.025)



```{r , include=FALSE}
library(knitr)
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')

#knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(fig.align='center',       comment='')
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
require(ggplot2)
require(scales) # to access break formatting functions
library(latex2exp)
library(pander)
panderOptions('knitr.auto.asis', FALSE)
library(plotly)
library(reticulate)
#use_python("/home/marco/Programs/Anaconda3/bin/python")

# library(knitrengines) # github.com/hrbrmstr/knitrengines
library(dplyr)
library(Rose)
library(ggrepel)


mom_lab<-function(vec){
  count=1
  r<- c()
  for(v in vec){
    if(v==0)
      r[count]="(0,0,0)"
    else if(v==1)
      r[count]="(1,0,0)"
    else if(v==2)
      r[count]="(1,1,0)"
    else if(v==3)
      r[count]="(1-1,0,0)"
    else if(v==4)
      r[count]="(1,1,1)"
    else
      r[count]="boh"
    count=count+1
  }
  return(r)
}
``` 



```{r, echo=FALSE, results='asis'}

 plot_QC3 <-function (basename, N){
file=sprintf("%s_fit_data.txt",basename)
df<- read.table(file, header=FALSE, fill=TRUE)

gg<- ggplot()
gg<-gg+  geom_point(data=df, mapping=aes(x=df[,1] , y=df[,2],
                          color=as.factor(df[,6]),
                          shape=as.factor(df[,6])) ,width=0.001)+labs(color = "momuntum")
gg<-gg + geom_errorbar(data=df, mapping=aes(x=df[,1] , ymin=df[,2]-df[,3],
                          ymax=df[,2]+df[,3],color=as.factor(df[,6]),
                          shape=as.factor(df[,6])) ,width=0.001)

df[,6]<-mom_lab(df[,6])
datalist = list()
for (n in c(1:N)){
  
file=sprintf("%s_fit_out_n%d_L.txt",basename,n-1)
datalist[[n]]<- read.table(file, header=FALSE, fill=TRUE,   
                 col.names=c(paste0("x",n),paste0("fit",n),paste0("fiterr",n)))

gg<-gg + geom_ribbon(data=datalist[[n]], mapping=aes_string(x=datalist[[n]][,1] , ymin=datalist[[n]][,2]-datalist[[n]][,3], ymax=datalist[[n]][,2]+datalist[[n]][,3]),alpha=0.5, fill="blue")
gg<-gg + geom_line(data=datalist[[n]], mapping=aes_string(x=datalist[[n]][,1] , y=datalist[[n]][,2] , shape=as.factor("fit") ),color="blue" )
#as.factor(n-1)
gg<-gg + geom_line(data=dfree[[n]], mapping=aes(x=L , y=E3_m , shape=as.factor("free")),color="red" )


}

fig<-myplotly(gg, "", "L","$E_3/m$", to_print=FALSE)
return(fig)
}
```




```{r, include=FALSE}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```


```{r, echo=FALSE}
file=sprintf("../../g0.025/fit_out/M0_finite_vol_fit_out_L.txt")
df_fit<- read.table(file, header=FALSE, fill=TRUE,col.names = c("L","M0L","M0L_err"))
m0=df_fit$M0L[length(df_fit[,1])]

dfree= list()
countfree=1
momenta<-list(c(0,0,0,0,0,0,0,0,0),c(1,0,0,0,0,0,0,0,0),c(1,1,0,0,0,0,0,0,0),c(1,0,0,-1,0,0,0,0,0), c(1,1,1,0,0,0,0,0,0))
for (p in momenta){
  myL<-c()
  myk<-c()
  E3_m<-c()
  for (L in c(23:40)){
    norm= p[1]^2+p[2]^2+p[3]^2
    norm=norm*(2*pi/L)^2
    norm1= p[4]^2+p[5]^2+p[6]^2
    norm1=norm1*(2*pi/L)^2
    norm2= p[7]^2+p[8]^2+p[9]^2
    norm2=norm2*(2*pi/L)^2
    norm_tot= (p[1]+p[4]+p[7])^2+(p[2]+p[5]+p[8])^2+(p[3]+p[6]+p[9])^2
    norm_tot=norm_tot*(2*pi/L)^2
    E2=sqrt(m0^2+norm1)+ sqrt(m0^2+norm )+ sqrt(m0^2+norm2 )
    E2cm=sqrt(E2^2-norm_tot)
    k=sqrt(E2cm^2/4. -m0^2)
    s=sprintf("(%d,%d,%d)(%d,%d,%d)",p[1],p[2],p[3],p[4],p[5],p[6])
    myL<-c(myL,L)
    myk<-c(myk,k)
    E3_m<-c(E3_m,E2/m0)
  }
  dfree[[countfree]]<-data.frame("L"=myL,"k"=myk,"E3_m"=E3_m)
  countfree=countfree+1
}
```




## p=(0,0,0)

### latt disp rel


```{r , child="../../g0.025/fit_out/QC3_N1_latt_1par_fit_P.tex", eval=TRUE}
```


```{r, echo=FALSE, results='asis'}

plot_QC3(basename="../../g0.025/fit_out/QC3_N1_latt_1par",N=1)
```



## p=(1,1,1)

### latt disp rel


```{r , child="../../g0.025/fit_out/QC3_N5_latt_1par_fit_P.tex", eval=TRUE}
```


```{r, echo=FALSE, results='asis'}

plot_QC3(basename="../../g0.025/fit_out/QC3_N5_latt_1par",N=5)
```


