## fit QC3 pole g=0.1



```{r , include=FALSE}
library(knitr)
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')

#knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(fig.align='center',       comment='')
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
require(ggplot2)
require(scales) # to access break formatting functions
library(latex2exp)
library(pander)
panderOptions('knitr.auto.asis', FALSE)
library(plotly)
library(reticulate)
#use_python("/home/marco/Programs/Anaconda3/bin/python")

# library(knitrengines) # github.com/hrbrmstr/knitrengines
library(dplyr)
library(Rose)
library(ggrepel)
``` 



```{r, include=FALSE}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```



minimizing the $\chi^2$
$$
\chi^2 =\sum_i  \frac{(E_3^{predicted} -E_3^{measured} )}{\sigma^2}
$$
the predicted energy is the solution of the three particles quantization condition
 in the isotropic approximation
$$
   F_3^{iso}(E,\vec P,L)=-1/K^{iso}_3(E^*)\,
$$
$F_3$ depend on the result of the two particle phase shift $\delta$ computed before and we parametrise $K_3^{iso}$ as 

$$
K_3^{iso}= \frac{P[0]}{E_{cm}^2-P[1]}
$$
where $P[1]$ represent the mass of the resonance $P[1]=M_R^2$



```{r , child="../../g0.1/fit_out/QC3_N1_2par_pole_fit_P.tex", eval=TRUE}
```



```{r, echo=FALSE}
file=sprintf("../../g0.1/fit_out/QC3_N1_2par_pole_fit_data.txt")
df<- read.table(file, header=FALSE, fill=TRUE)
names(df) <- c("$L$","$E_3/m$","err", "$T$","$q2$")
df<- df[c("$T$","$L$","$E_3/m$","err" ,"$q2$")] 
#kable(df[,-5],digit=20)
```





```{r, echo=FALSE, results='asis'}
file=sprintf("../../g0.1/fit_out/QC3_N1_2par_pole_fit_data.txt")
df<- read.table(file, header=FALSE, fill=TRUE)

gg<- ggplot()
gg<-gg+  geom_point(data=df, mapping=aes(x=df[,1] , y=df[,2],
                          color=as.factor(df[,6]),
                          fill=as.factor(df[,6])) ,width=0.001)+labs(color = "momuntum")
gg<-gg + geom_errorbar(data=df, mapping=aes(x=df[,1] , ymin=df[,2]-df[,3],
                          ymax=df[,2]+df[,3],color=as.factor(df[,6]),
                          fill=as.factor(df[,6])) ,width=0.001)
mom_lab<-function(vec){
  count=1
  r<- c()
  for(v in vec){
    if(v==0)
      r[count]="(0,0,0)"
    else if(v==1)
      r[count]="(0,0,0)"
    else if(v==2)
      r[count]="(1,0,0)"
    else if(v==3)
      r[count]="(1,0,0)"
    else if(v==4)
      r[count]="(1,1,0)"
    else if(v==5)
      r[count]="(1,1,0)"
    else
      r[count]="boh"
    count=count+1
  }
  return(r)
}
df[,6]<-mom_lab(df[,6])
datalist = list()
for (n in c(1:1)){
  
file=sprintf("../../g0.1/fit_out/QC3_N1_2par_pole_fit_out_n%d_L.txt",n-1)
datalist[[n]]<- read.table(file, header=FALSE, fill=TRUE,   
                 col.names=c(paste0("x",n),paste0("fit",n),paste0("fiterr",n)))
datalist[[n]]$v<-mom_lab(n-1)
gg<-gg + geom_ribbon(data=datalist[[n]],
                     mapping=aes_string(x=datalist[[n]][,1] ,
                            ymin=datalist[[n]][,2]-datalist[[n]][,3],
                            ymax=datalist[[n]][,2]+datalist[[n]][,3],
                            color=as.factor(datalist[[n]]$v), 
                            fill=as.factor(datalist[[n]]$v) ),
                     alpha=0.5)
#gg<-gg + geom_line(data=datalist[[n]],
#                   mapping=aes_string(x=datalist[[n]][,1] ,
#                              y=datalist[[n]][,2],
#                              color=datalist[[n]]$v) )
#as.factor(n-1)
#gg<-gg + geom_line(data=dfree[[n]], mapping=aes(x=L , y=E3_m ),color="red" )


}

fig<-myplotly(gg, "", "L","$E_3/m$")
```
