# GEVP g0.025 

```{r  include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
 #library(sigma)
 source('functions.R')
```

we construct the matrix 

$$
C(t)=\begin{pmatrix}
\langle\phi_0(0)\phi_0(t) \rangle  & \langle\phi_0^3(0)\phi_0(t)  & \langle\phi_0(0)\phi_1(t) \rangle   \rangle  \\
 & \langle\phi_0^3(0)\phi_0^3(t) \rangle  & \langle\phi_0^3(0)\phi_1(t) \rangle \\
 & &\langle\phi_1(0)\phi_1(t) \rangle  
\end{pmatrix}
$$
we do not wtrite the lower triangular part of the matrix since $C$ is hermitian so
$C_{ij}=C_{ji}^*$. We solve the GEVP
$$
  C(t)v_n(t,t_0)=\lambda_n(t,t_0)C(t_0) v_n(t,t_n)
$$
and we get $\lambda_n(t,t_0)$ which we fit as
$$
\lambda_n(t,t_0)=C \left(e^{ - E_n  (t-t_0)}  + e^{ - E_n  ((T - t)-t_0)}\right)
$$

```{r, echo=FALSE,results='asis'}



gg<-ggplot()
T<- 32
L<- 28
# dir<-paste("../out")
# file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output",dir,T,L)
dir<-paste("../../g0.025/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.025000_rep0_output",dir,T,L)

cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)

#gg<-add_plot("E3_0_vev",all_obs,mt,gg,"yes")
#gg<-add_plot("E3_0_p1",all_obs,mt,gg,"yes")
#gg<-add_plot("E3_0_p11",all_obs,mt,gg,"yes")
#gg<-add_plot("E3_0_p111",all_obs,mt,gg,"yes")
gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
gg<-add_plot("E1_0",all_obs,mt,gg,"no")
gg<-add_plot("E1_1",all_obs,mt,gg,"no")
# fig<-ggplotly(gg)%>% layout(title="fit" ,xaxis = list(title = "$t$",showexponent = "all", exponentformat = "e" , autorange = T  ) ,
#                       yaxis = list(title = "$\\log c(t)$",showexponent = "all", exponentformat = "e", autorange = T  ))  
# print(htmltools::tagList(fig))

fig<- myplotly(gg,"fit","t", "y" )


```