## GEVP P=(0,0,0) g0.1 {#GEVP_p0_g0_1}

```{r  include=FALSE}
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')
 
 library(ggplot2)
 library(plotly)
 library(tidyverse)
 library(htmlwidgets)
 library(pander)
 #library(latex2exp)
 library(knitr)
 library(dplyr) #data frame manipulation
 require(scales) # to access break formatting functions
 #library(shiny)
 #library(shinyWidgets)
 library(ggrepel)
 library(Rose)
 library(widgetframe)
 require("processx")
 library(webshot)
 library(htmltools)
 #library(sigma)
 source('functions.R')
```




```{r, echo=FALSE,results='asis'}
df<-data.frame("L"=c(0),"T"=c(0),"E3"=c(0),"E3err"=c(0),"E1"=c(0),"E1err"=c(0),
               "E3p1"=c(0),"E3p1err"=c(0),"E1p1"=c(0),"E1p1err"=c(0))
df<-df[-1,]
gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")
mt<-read_df(file)
all_obs<- get_all_corr(mt)

 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_vev",all_obs,mt,gg,"no")

 # gg<-add_plot("GEVP_0_3_1_A1_meffl0",all_obs,mt,gg,"no")
 # gg<-add_plot("GEVP_0_3_1_A1_meffl1",all_obs,mt,gg,"no")
 # gg<-add_plot("GEVP_0_3_1_A1_meffl2",all_obs,mt,gg,"no")
 # gg<-add_plot("GEVP_0_3_1_A1_meffl3",all_obs,mt,gg,"no")
 
 
fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )

df[length(df[,1])+1,]<-list(L,T,
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[2]
                          )


```



```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 26

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)

 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )


df[length(df[,1])+1,]<-list(L,T,
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[2]
                          )

```



```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 36

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)

 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )


df[length(df[,1])+1,]<-list(L,T,
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt)[2],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[1],
                          get_energy("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt)[2]
                          )

```


```{r}
gg<-ggplot()
gg<- gg+ geom_point(data=df,mapping=aes(x=L, y=E3, color="$3\\phi_0$"))
gg<- gg+ geom_errorbar(data=df,mapping=aes(x=L, ymin=E3-E3err, ymax=E3+E3err, color="$3\\phi_0$"), width=0.3)
gg<- gg+ geom_point(data=df,mapping=aes(x=L, y=E1, color="$\\phi_1$"))
gg<- gg+ geom_errorbar(data=df,mapping=aes(x=L, ymin=E1-E1err, ymax=E1+E1err, color="$\\phi_1$"), width=0.3)
myplotly(gg,"","L","E(p=(0,0,0))",to_print=FALSE)
```

## GEVP P=(1,0,0) g0.1 {#GEVP_p1_g0_1}


```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 26

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
 for (comp in c(0:2)){
   l<-list()
   for (i in c(0:2)){
      name<-paste0("GEVP_phi0_phi03_phi1_p1_v",i,"_",comp)
      ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
      l<-append(l,get_energy(name,all_obs,mt))
   }
   dfv[comp+1,]<-l
 }
 kable(dfv)
 figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes")
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes")
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes")
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```


```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("## ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
 for (comp in c(0:2)){
   l<-list()
   for (i in c(0:2)){
      name<-paste0("GEVP_phi0_phi03_phi1_p1_v",i,"_",comp)
      ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
      l<-append(l,get_energy(name,all_obs,mt))
   }
   dfv[comp+1,]<-l
 }
 kable(dfv)
 figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```

## t0=10 GEVP 



```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output_GEVP10",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
 for (comp in c(0:2)){
   l<-list()
   for (i in c(0:2)){
      name<-paste0("GEVP_phi0_phi03_phi1_p1_v",i,"_",comp)
      ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
      l<-append(l,get_energy(name,all_obs,mt))
   }
   dfv[comp+1,]<-l
 }
 kable(dfv)
 figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```



## m0=-.893 GEVP 



```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.893000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
 # for (comp in c(0:2)){
 #   l<-list()
 #   for (i in c(0:2)){
 #      name<-paste0("GEVP_phi0_phi03_phi1_p1_v",i,"_",comp)
 #      ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
 #      l<-append(l,get_energy(name,all_obs,mt))
 #   }
 #   dfv[comp+1,]<-l
 # }
 # kable(dfv)
 # figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
 ggl<-add_plot("GEVP_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```

## t0=t+3 GEVP 

here we solve the GEVP 
$$
C(t)v(t,t_0)= \lambda(t,t_0)C(t_0) v(t,t_0)
$$
for $t_0=t+3$. the corresponding eigenvalue in the case $T\to \infty$
$$
\lambda_n(t,t_0)= e^{-E_n(t-t_0)}= e^{-3 E_n}
$$

```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
  for (comp in c(0:2)){
    l<-list()
    for (i in c(0:2)){
       name<-paste0("GEVP_tpt0_phi0_phi03_phi1_p1_v",i,"_",comp)
       ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
       l<-append(l,get_energy(name,all_obs,mt))
    }
    dfv[comp+1,]<-l
  }
 kable(dfv)
 figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
 ggl<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
 ggl<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
 # gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
 # gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
 # gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```




## t=3 t0 variable  GEVP 

here we solve the GEVP 
$$
C(t)v(t,t_0)= \lambda(t,t_0)C(t_0) v(t,t_0)
$$

for fixed $t=3$ for all $t0$

```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
                "v1"=c(0), "v1_err"=c(0),
                "v2"=c(0), "v2_err"=c(0))
  for (comp in c(0:2)){
    l<-list()
    for (i in c(0:2)){
       name<-paste0("GEVP_swap_t_t0_phi0_phi03_phi1_p1_v",i,"_",comp)
       ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
       l<-append(l,get_energy(name,all_obs,mt))
    }
    dfv[comp+1,]<-l
  }
 kable(dfv)
 figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )

 ggl<-ggplot()
 ggl<-add_plot("GEVP_swap_t_t0_phi0_phi03_phi1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
 ggl<-add_plot("GEVP_swap_t_t0_phi0_phi03_phi1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
 ggl<-add_plot("GEVP_swap_t_t0_phi0_phi03_phi1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
 figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )

 
 
  gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
  gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
  gg<-add_plot("GEVP_tpt0_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```


## Gevp 4x4

the GEVP 4x4 does not work the matrix is not positive define, I could not find the error 

```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 28

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)
ggv<-ggplot()
# dfv<-data.frame("v0"=c(0), "v0_err"=c(0),
#                 "v1"=c(0), "v1_err"=c(0),
#                 "v2"=c(0), "v2_err"=c(0),
#                 "v3"=c(0), "v3_err"=c(0) )
#  for (comp in c(0:3)){
#    l<-list()
#    for (i in c(0:3)){
#       name<-paste0("GEVP_0_3_1_A1_p1_v",i,"_",comp)
#       ggv<-add_plot(name,all_obs,mt,ggv,"no",nudge=0.1*(comp+i))
#       l<-append(l,get_energy(name,all_obs,mt))
#    }
#    dfv[comp+1,]<-l
#  }
#  kable(dfv)
#  figv<- myplotly(ggv,"eigenvectors","t", "y", to_print=TRUE, width = 900 )
# 
#  ggl<-ggplot()
#  ggl<-add_plot("GEVP_0_3_1_A1_p1_l0",all_obs,mt,ggl,"yes",nudge=0)
#  ggl<-add_plot("GEVP_0_3_1_A1_p1_l1",all_obs,mt,ggl,"yes",nudge=0.1)
#  ggl<-add_plot("GEVP_0_3_1_A1_p1_l2",all_obs,mt,ggl,"yes",nudge=0.2)
#  ggl<-add_plot("GEVP_0_3_1_A1_p1_l3",all_obs,mt,ggl,"yes",nudge=0.2)
#  figl<- myplotly(ggl,"eigenvalues","t", "$\\log \\lambda$", to_print=TRUE, width = 900 )
# 
#  
 
 gg<-add_plot("GEVP_0_3_1_A1_p1_meffl0",all_obs,mt,gg,"no",nudge=0)
 gg<-add_plot("GEVP_0_3_1_A1_p1_meffl1",all_obs,mt,gg,"no",nudge=0.1)
 gg<-add_plot("GEVP_0_3_1_A1_p1_meffl2",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("GEVP_0_3_1_A1_p1_meffl3",all_obs,mt,gg,"no",nudge=0.2)
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"masses","t", "y", to_print=TRUE, width = 900 )


```



```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 30

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)


 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )


```




```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 36

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)


 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p1_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0_px",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_px",all_obs,mt,gg,"no")
 gg<-add_plot("phi03_p1_meff",all_obs,mt,gg,"no")
 gg1<-add_plot("E3_0_p1_vev",all_obs,mt,gg,"no")

fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )


```





```{r}
gg<-ggplot()
df$E3p1cm<- sqrt(df$E3p1^2-(2*pi/df$L)^2)
df$E3p1cmerr<- 2*df$E3p1*df$E3p1err/ sqrt(df$E3p1^2-(2*pi/df$L)^2)

df$E1p1cm<- sqrt(df$E1p1^2-(2*pi/df$L)^2)
df$E1p1cmerr<- 2*df$E1p1*df$E1p1err/ sqrt(df$E1p1^2-(2*pi/df$L)^2)


gg<- gg+ geom_point(data=df,mapping=aes(x=L, y=E3p1cm, color="$3\\phi_0$"))
gg<- gg+ geom_errorbar(data=df,mapping=aes(x=L, ymin=E3p1cm-E3p1cmerr, ymax=E3p1cm+E3p1cmerr, color="$3\\phi_0$"), width=0.3)
gg<- gg+ geom_point(data=df,mapping=aes(x=L, y=E1p1cm, color="$\\phi_1$"))
gg<- gg+ geom_errorbar(data=df,mapping=aes(x=L, ymin=E1p1cm-E1p1cmerr, ymax=E1p1cm+E1p1cmerr, color="$\\phi_1$"), width=0.3)
myplotly(gg,"","L","E_{CM}(p=(1,0,0))",to_print=FALSE)
```





## GEVP P=(1,1,0) g0.1 {#GEVP_p11_g0_1}


```{r, echo=FALSE,results='asis'}


gg<-ggplot()
T<- 64
L<- 24

dir<-paste("../../g0.1/out")
file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.100000_rep0_output",dir,T,L)
cat("### ",file,"\n\n")

mt<-read_df(file)
all_obs<- get_all_corr(mt)


 gg<-add_plot("GEVP_phi0_phi03_phi1_p11_meffl0",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p11_meffl1",all_obs,mt,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_p11_meffl2",all_obs,mt,gg,"no")
 gg<-add_plot("E1_0_p11",all_obs,mt,gg,"no")
 gg<-add_plot("E1_1_pxy",all_obs,mt,gg,"no")
 
fig<- myplotly(gg,"fit","t", "y", to_print=TRUE, width = 900 )


```





```{r, include=FALSE}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```