# report fit $m_0$

```{r , include=FALSE}
library(knitr)
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')

#knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(fig.align='center',       comment='')
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
require(ggplot2)
require(scales) # to access break formatting functions
library(latex2exp)
library(pander)
panderOptions('knitr.auto.asis', FALSE)
library(plotly)
library(reticulate)
use_python("/home/marco/Programs/Anaconda3/bin/python")

# library(knitrengines) # github.com/hrbrmstr/knitrengines
library(dplyr)
library(Rose)
library(ggrepel)

``` 


```{r, echo=FALSE}
file=sprintf("../prova/M0_finite_vol_fit_data.txt")
df<- read.table(file, header=FALSE, fill=TRUE)
names(df) <- c("$L$","$M_0(L)$","err", "$T$")
df<- df[c("$T$","$L$","$M_0(L)$","err" )] 
kable(df,digit=20)
```

$$
M_0(L)=P[0]  +P[1] \frac{e^{-ML}}{(ML)^{3/2}}
$$


```{r , child="../prova/M0_finite_vol_fit_P.tex", eval=TRUE}
```



```{r,echo=FALSE}
file=sprintf("../prova/M0_finite_vol_fit_data.txt")
df<- read.table(file, header=FALSE, fill=TRUE,col.names = c("L","M0L","M0L_err", "T","k","n"))
file=sprintf("../prova/M0_finite_vol_fit_out_L.txt")
df_fit<- read.table(file, header=FALSE, fill=TRUE,col.names = c("L","M0L","M0L_err"))
gg<- ggplot()
#gg<-gg+ geom_point(data=df, mapping=aes(x=L , y=M0L) )
gg<-gg + geom_errorbar(data=df, mapping=aes(x=L , ymin=M0L-M0L_err, ymax=M0L+M0L_err),color="blue" ,width=0.2)
gg<-gg + geom_ribbon(data=df_fit, mapping=aes(x=L , ymin=M0L-M0L_err, ymax=M0L+M0L_err),fill="blue",alpha=0.2)
gg<-gg + geom_text_repel(data=df, mapping=aes(x=L,  y=M0L, label=T))
#gg<- gg + xlim(18 ,36) +ylim(0.145,0.149)
#gg<- gg +labs(x = TeX('L/a'), y= TeX('$M_0(L)$'))

gg<- gg+theme_bw() +ggplot2::coord_cartesian(xlim=c(20,45), ylim=c(0.1275,0.130 ))
ggplotly(gg)
m0=df_fit$M0L[length(df_fit[,1])]
```



