# test area



```{r, echo=FALSE,results='asis'}



gg<-ggplot()
T<- 32
L<- 24
 dir<-paste("../out")
 file=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output",dir,T,L)
 
T<- 32
L<- 28
dir<-paste("../../g0.025/out")
file1=sprintf("%s/G2t_T%d_L%d_msq0-4.900000_msq1-4.650000_l02.500000_l12.500000_mu5.000000_g0.025000_rep0_output",dir,T,L)

cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)


mt1<-read_df(file1)
all_obs1<- get_all_corr(mt1)


#gg<-add_plot("E1_0",all_obs,mt,gg,"no")
#gg<-add_plot("E1_1",all_obs,mt,gg,"no")
#gg<-add_plot("fun_l1_GEVP",all_obs,mt,gg,"no")
#gg<-add_plot("E3_0_vev",all_obs,mt,gg,"no")
#gg<-add_plot("E3_0_p111",all_obs,mt,gg,"yes")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l0",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l1",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l2",all_obs,mt,gg,"no")


# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
# gg<-add_plot("fun_l1_GEVP",all_obs,mt,gg,"no")
# gg<-add_plot("E3_0_vev",all_obs,mt,gg,"no")

 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs1,mt1,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs1,mt1,gg,"no")
 gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs1,mt1,gg,"no")
 gg<-add_plot("E1_0",all_obs1,mt1,gg,"no")
 gg<-add_plot("E1_1",all_obs1,mt1,gg,"no")

# fig<-ggplotly(gg)%>% layout(title="fit" ,xaxis = list(title = "$t$",showexponent = "all", exponentformat = "e" , autorange = T  ) ,
#                       yaxis = list(title = "$\\log c(t)$",showexponent = "all", exponentformat = "e", autorange = T  ))  
# print(htmltools::tagList(fig))

fig<- myplotly(gg,"fit","t", "y" , width=1000 )


```


```{r, echo=FALSE, eval=FALSE}
cor<- c()
m<- 0.127893
E3<-0.4101
A1<-0.01
A2<-0.03

t<-c(1:160)/10
cor<-c(cor, A1*cosh(E3*(t-T/2) )+A2*cosh(m*(t-T/2)) )
gg<-ggplot()

gg<-add_plot("GEVP_phi0_phi03_phi1_l0",all_obs1,mt1,gg,"yes")
gg<-add_plot("GEVP_phi0_phi03_phi1_l1",all_obs1,mt1,gg,"yes")
gg<-add_plot("GEVP_phi0_phi03_phi1_l2",all_obs1,mt1,gg,"yes")
gg<- gg+ geom_line(aes(x=t,y=log10(cor)))
fig<- myplotly(gg,"fit","t", "y", to_print = TRUE )

```


```{r,results='asis'}
gg<- ggplot()
gg<-add_res_plot("E3_0_vev",all_obs,mt,gg,"no")
fig<- myplotly(gg,"fit","t", "y", to_print = FALSE )
fig
```


```{r, echo=FALSE,results='asis' ,dev='tikz'}

gg<-ggplot()
T<- 16
L<- 4
 dir<-paste("/home/marco/programs/Z2-phi4/build/main/data/out")
 file=sprintf("%s/G2t_T%d_L%d_msq0-4.850000_msq1-4.850000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_output",dir,T,L)
 
cat("\n####",file,'\n\n')

mt<-read_df(file)
all_obs<- get_all_corr(mt)



#gg<-add_plot("E1_0",all_obs,mt,gg,"no")
#gg<-add_plot("sE1_0",all_obs,mt,gg,"no")

gg<-add_plot("E1_0",all_obs,mt,gg,"no")
gg<-add_plot("sE1_0",all_obs,mt,gg,"no")

gg<-add_plot("E2_0",all_obs,mt,gg,"no")
gg<-add_plot("sE2_0",all_obs,mt,gg,"no")

gg<-add_plot("E3_0_vev",all_obs,mt,gg,"yes")
gg<-add_plot("sE3_0_vev",all_obs,mt,gg,"yes")


#gg<-add_plot("fun_l1_GEVP",all_obs,mt,gg,"no")
#gg<-add_plot("E3_0_vev",all_obs,mt,gg,"no")
#gg<-add_plot("E3_0_p111",all_obs,mt,gg,"yes")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l0",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l1",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_l2",all_obs,mt,gg,"no")


# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs,mt,gg,"no")
# gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs,mt,gg,"no")
# gg<-add_plot("fun_l1_GEVP",all_obs,mt,gg,"no")
# gg<-add_plot("E3_0_vev",all_obs,mt,gg,"no")

 #gg<-add_plot("GEVP_phi0_phi03_phi1_meffl0",all_obs1,mt1,gg,"no")
 #gg<-add_plot("GEVP_phi0_phi03_phi1_meffl1",all_obs1,mt1,gg,"no")
 #gg<-add_plot("GEVP_phi0_phi03_phi1_meffl2",all_obs1,mt1,gg,"no")
 #gg<-add_plot("E1_0",all_obs1,mt1,gg,"no")
 #gg<-add_plot("E1_1",all_obs1,mt1,gg,"no")

fig<- myplotly(gg,"fit","t", "y", width=900, yrange = c(-3,5) )


```






```{r, include=FALSE}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```