
# Fit 2 particle quantization (g=0.025)


```{r , include=FALSE}
library(knitr)
 knitr::opts_chunk$set(echo = FALSE, warning = FALSE, result='asis')

#knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(fig.align='center',       comment='')
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
require(ggplot2)
require(scales) # to access break formatting functions
library(latex2exp)
library(pander)
panderOptions('knitr.auto.asis', FALSE)
library(plotly)
library(reticulate)
use_python("/home/marco/Programs/Anaconda3/bin/python")

# library(knitrengines) # github.com/hrbrmstr/knitrengines
library(dplyr)
library(Rose)
library(ggrepel)
``` 


```{r include=FALSE}
library(ggplot2)
library(plotly)
df <- data.frame(x = 1:5, y = 1:5)    
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knitr handle the rendering naturally
```




```{r , child="../../g0.025/fit_out/deltaE2_m_quant_cond_fit_P.tex", eval=TRUE}
```





```{r, echo=FALSE, results='asis'}
file=sprintf("../../g0.025/fit_out/deltaE2_m_quant_cond_fit_data.txt")
df<- read.table(file, header=FALSE, fill=TRUE)


gg<- ggplot()
gg<-gg+  geom_point(data=df, mapping=aes(x=df[,1] , y=df[,2],
                          color=as.factor(df[,6]), shape=as.factor(df[,6])) ,width=0.001)+labs(color = "momentum", shape="momentum")
gg<-gg + geom_errorbar(data=df, mapping=aes(x=df[,1] , ymin=df[,2]-df[,3],
               ymax=df[,2]+df[,3],color=as.factor(df[,6]),shape=as.factor(df[,6]) ) ,width=0.001)
mom_lab<-function(vec){
  count=1
  r<- c()
  for(v in vec){
    if(v==0)
      r[count]="(0,0,0)"
    else if(v==1)
      r[count]="(1,0,0)"
    else if(v==2)
      r[count]="(1,1,0)"
    else if(v==3)
      r[count]="(1-1,0,0)"
    else if(v==4)
      r[count]="(1,1,1)"
    else
      r[count]="boh"
    count=count+1
  }
  return(r)
}
df[,6]<-mom_lab(df[,6])
datalist = list()
for (n in c(1:5)){
  
file=sprintf("../../g0.025/fit_out/deltaE2_m_quant_cond_fit_out_n%d_L.txt",n-1)
datalist[[n]]<- read.table(file, header=FALSE, fill=TRUE,   
                 col.names=c(paste0("x",n),paste0("fit",n),paste0("fiterr",n)))

gg<-gg + geom_ribbon(data=datalist[[n]], mapping=aes_string(x=datalist[[n]][,1] , ymin=datalist[[n]][,2]-datalist[[n]][,3], ymax=datalist[[n]][,2]+datalist[[n]][,3]),alpha=0.5, fill="blue")
gg<-gg + geom_line(data=datalist[[n]], mapping=aes_string(x=datalist[[n]][,1] , y=datalist[[n]][,2]  ),color="blue" )


}

gg<- gg+theme_bw() #+ ggplot2::coord_cartesian(xlim=c(0,0.05), ylim=c(-3,0 ))


# fig_pdf<- myplotly(gg,"", "$L$", "$E_2- E_{free}^{lat}+E_{free}^{cont}/m$", xrange=c(26, 40),yrange=c(2,4.5), output="PDF",to_print = FALSE)
#library(ggforce)
#fig_pdf<- fig_pdf+ facet_zoom(ylim = c(2.65, 2.75))
# save_pdf = "pdf_figs/E2_latt_fit"
#       texfile=paste0(save_pdf,".tex")
#       tikzDevice::tikz(texfile,standAlone=TRUE, width = 8, height = 4)
#       plot(fig_pdf)
#       dev.off()
#       tools::texi2dvi(paste0(save_pdf,".tex"),pdf=TRUE)
# 
fig<- myplotly(gg,"fit", "L", "$E_2- E_{free}^{lat}+E_{free}^{cont}/m$", xrange=c(23, 40) , yrange=c(1.8,5))


```